- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true
  tags:
    - homebrew_packages
    - homebrew_casks

- name: Add Homebrew taps
  community.general.homebrew_tap:
    state: present
    name: '{{ item }}'
  loop: '{{ homebrew_taps }}'
  tags:
    - homebrew_packages
    - homebrew_casks

- name: Update all installed Homebrew packages
  community.general.homebrew:
    upgrade_all: true
  tags:
    - homebrew_packages
    - homebrew_casks

- name: Install Homebrew packages
  community.general.homebrew:
    state: present
    name: '{{ item }}'
  loop: '{{ homebrew_packages }}'
  tags:
    - homebrew_packages

- name: Install Homebrew cask apps
  community.general.homebrew_cask:
    state: present
    name: '{{ item }}'
  loop: '{{ homebrew_cask_apps }}'
  ignore_errors: true
  tags:
    - homebrew_casks

- name: Cleanup Homebrew
  ansible.builtin.shell: brew cleanup
  tags:
    - homebrew_packages
    - homebrew_casks
