- name: Set content of sudo file as fact
  set_fact:
    sudo_conf: "{{ lookup('file', '/etc/pam.d/sudo') }}"
  ignore_errors: yes
  tags:
    - touchid

- name: Set sudo via Touch ID if not setup
  become: yes
  command: sed -i '' 's/auth       sufficient     pam_smartcard.so/auth       sufficient     pam_smartcard.so\nauth       sufficient     pam_tid.so/g' /etc/pam.d/sudo
  when: "'auth       sufficient     pam_tid.so' not in sudo_conf"
  tags:
    - touchid

- name: Install Apps from the Mac App Store
  community.general.mas:
    id: '{{ item }}'
  loop: '{{ mac_app_store_app_ids }}'
  tags:
    - mas
